### ISSUE TITLE
En Passant

### ISSUE THREAD

**Issue by ZohaibBhatti05** [ZobearBhatti/MonogameChess#1]
En Passant uses the opposing pawn's previous rank, which works fine, but makes en passant "legal" even if turns have passed (making it no longer valid)

**Comment by FoxH22** [comment]
> En Passant uses the opposing pawn's previous rank, which works fine, but makes en passant "legal" even if turns have passed (making it no longer valid)

unlucky really

**Comment by ZohaibBhatti05** [comment]
You are some smelly guy
